### ISSUE TITLE
Function not returning standard out

### ISSUE THREAD

**Issue by ghost** [bhendo/go-powershell#7]
I am using another application which implements your module. I am not sure if the problem is with the implementation, or if the problem is with the function here. I have created an issue with the other project here [pssession isn't working with msdns provider](https://github.com/StackExchange/dnscontrol/issues/1104)

But figured I would bring it up here as well. Debugging I narrowed it down to line 41 of [session.go](https://github.com/bhendo/go-powershell/blob/219e7fb4e41e15c1a8f68c7f082c4c6df96d6362/middleware/session.go#L41) 

```go
return s.upstream.Execute(fmt.Sprintf("Invoke-Command -Session $%s -Script {%s}", s.name,cmd))
```

The PowerShell passed into `%s` was valid from my testing (and I was able to execute it on the same system with a separate PowerShell shell), but from go nothing returned to stdout from this function, nor are there any errors.

**Comment by bhendo** [comment]
Hi, thank you for reaching out. I'm not actively maintaining this repository. In fact, I'm surprised to see it used by such a large project like DNSControl. This is a copy hosted by me for historical purposes, the original maintainers deleted their repository. That said, feel free to fork and PR a fix, I'll be happy to review and include it.
